# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Xiaowen Chen
tagline:          'Theoretical biophysics'
description:      'PhD candidate at Princeton University'
url:              http://xiaowen-chen.github.io/
baseurl:          /

author:
  name:           'Xiaowen Chen'
  url:            https://google.com

theme: jekyll-theme-minimal
